import Head from "next/head";
import { useTheme } from "next-themes";
import { useEffect, useState } from "react";

export default function Controls() {
  const { theme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  /**
   * Prevents Next.js hydration mismatch error
   * @see https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch
   */
  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <>
      <Head>
        <title>Controls</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col gap-3 items-center justify-center min-h-screen">
        <h1 className="text-3xl font-semibold text-center">Controls</h1>

        <button
          type="button"
          className="bg-primary-light dark:bg-primary-dark font-semibold text-2xl p-3 rounded-lg"
          onClick={() => setTheme(theme === "light" ? "dark" : "light")}
        >
          Toggle Theme
        </button>
      </main>
    </>
  );
}
