import Head from "next/head";
import { useTheme } from "next-themes";
import { useEffect, useState } from "react";

export default function Home() {
  const { theme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  /**
   * Prevents Next.js hydration mismatch error
   * @see https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch
   */
  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-light-theme font-sans dark:font-serif dark:text-dark-theme text-3xl font-semibold text-center">
          Hello World
        </h1>
        <button
          type="button"
          className="bg-primary-light dark:bg-primary-dark"
          onClick={() => setTheme(theme === "light" ? "dark" : "light")}
        >
          {theme}
        </button>
      </main>
    </>
  );
}
