import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const { push } = useRouter();

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row gap-x-5 items-center justify-center min-h-screen text-3xl font-semibold">
        <button
          className="border-2 border-solid p-3 border-black dark:border-white rounded-lg"
          type="button"
          onClick={() => push("/products")}
        >
          Products
        </button>

        <button
          className="border-2 border-solid p-3 border-black dark:border-white rounded-lg"
          type="button"
          onClick={() => push("/controls")}
        >
          Controls
        </button>
      </main>
    </>
  );
}
