import Head from "next/head";
import { type Product } from "../utils/ProductSchema";
import { ProductCard1, ProductCard2 } from "../components";

export default function Products({ products }: { products: Product[] }) {
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col gap-3 items-center justify-center min-h-screen">
        <h1 className="text-6xl font-bold text-center">Products</h1>

        <ProductCard1 product={products[0]} />
        <ProductCard2 product={products[0]} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const res = await fetch("https://dummyjson.com/products");
    const data = await res.json();

    // Ensure that the data is an array of products
    const products: Product[] = Array.isArray(data.products)
      ? data.products
      : [];

    return { props: { products } };
  } catch (error) {
    console.error(error);
    return { props: { products: [] } };
  }
}
