import Head from "next/head";

export default function Products() {
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col gap-3 items-center justify-center min-h-screen">
        <h1 className="text-3xl font-semibold text-center">Products</h1>
      </main>
    </>
  );
}
